### ISSUE TITLE
[Feature] Use better emoji & font

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#10]
Could be cool to change the default font to something like Poppins (which imho looks rly better than sans-serif) and emojis to Apple one's (if installed) or by twitter's if apple one are not installed cuz for now I'm having issues with emojis :
![Kuvakaappaus 2022-01-25 16-58-36](https://user-images.githubusercontent.com/57091497/151012130-9a3c6f3e-53ae-4ff3-9885-25ed66f5d6ed.png)
/

**Comment by Shirajuki** [comment]
Thanks for the suggestion @ebanDev. It would be cool to be able to change fonts indeed!
However, I would need to have to take a look at which font to be used on the finalized redesign on a later update as one need to manually download that specific font for it to work. I am afraid some might find that troublesome. I have for now added the option to change the font yourself through the `config.json` file (will be featured on the v0.0.7 release). The plan is to move all Anki-redesign configurations/customizations to an user-friendly dialog window as suggested in issue #9 in the future.

I'll hope you will look forward to the future updates, where I soon will look into this issue again. I'll be closing this for now :) Overall, I would like to thank you very much for all your suggestions!
