### ISSUE TITLE
[Style, Feature] Apply main color to anki links

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#14]
![Kuvakaappaus 2022-01-25 17-18-15](https://user-images.githubusercontent.com/57091497/151016087-5e993ebf-21e6-418a-96ec-9e17a8ab154b.png)
I set my main color to purple, and the link and sync button are still blue :(

**Comment by Shirajuki** [comment]
Hello @ebanDev!
Do not worry about making a lot of issues, I am on the other hand actually happy that you did so. I can't thank you enough for the time you've spent to help with improvement of the addon. I have had quite a busy week this week and did therefore not have the time to reply your issues earlier, but I have taken a thoroughly look at them all now and they seem all very good! I'll be including fixes for most of the issues soon, some of the enhancement/feature requests however will take a little bit more time to implement, so I hope you'll wait for it on the future updates!

Thank you very much for being an user of Anki-redesign, and your issues!

**Comment by Shirajuki** [comment]
Hello again!
I have now added support for customizing the link color featured in the release v0.0.7. As I can't seem to get to the same view as you, I couldn't test the implementation that much. Hopefully it will be looking better for you after the update! :D
Again, I'll keep the issue open in case the fix did not work for you. :)

**Comment by ebanDev** [comment]
Since your update, the "sync" button just doesn't have color anymore :/
![Kuvakaappaus 2022-02-02 10-30-02](https://user-images.githubusercontent.com/57091497/152127833-ad613025-c5b6-4142-951b-5fd113913edf.png)

**Comment by Shirajuki** [comment]
Hello again, sorry for the late reply. I have been quite busy with studies for the last months. Since the new major update after commit c64c34de94cf46a63cd8c808ed73eb882a80257d, customizing hyperlinks now work as they should :D

I'll be closing this issue for now, feel free to reopen this if the problem still occurs. Thank you very much for being an user of Anki-redesign!
