### ISSUE TITLE
Advanced Review Bottom Bar Plug-In Breaks "Study Now" buttom (Minor Issue)

### ISSUE THREAD

**Issue by aidan-gibson** [Shirajuki/anki-redesign#22]
[Anki-Advanced-Review-Bottombar](https://github.com/noobj2/Anki-Advanced-Review-Bottombar) makes "Study Now" buttom appear wrong.
![image](https://user-images.githubusercontent.com/20917687/168866172-32134043-8f20-4896-bdd7-56486ce3ba42.png)

Extremely minor issue.

Thank you for this awesome redesign!

**Comment by Shirajuki** [comment]
Hello hello!
Thank you very much for the issue. I am lil bit busy with exam reading for the time being, but I will definitely take a look at this and hopefully get a compatibility fix for the addon in the next update! :D

Thank you for being a user of Anki-Redesign as well! 🥳

**Comment by ryryjy** [comment]
Hello. Thank you for this classy add-on. I would like to add on the inconsistency of buttons when customized button sizes are enabled in ARBB. The redesign add-on doesn't seem to comply with ARBB's custom button size settings. Also, the remaining cards info looks a bit awkward (maybe add a border line at the top of the bottom bar?).
![unknown](https://user-images.githubusercontent.com/36298836/175924068-c7d272a9-eacd-4813-b53e-17f159bd6f8b.png)

No rush on the work. I use hotkeys anyway on my case.

**Comment by Shirajuki** [comment]
Hello!
Thank you for a detailed report showing the issue with very informative images! Seeing the problem visually does help me a lot with the debugging!
I am currently in the works of figuring out a solution for this problem, hopefully an update resolving this issue will come out before the end of this month. :D

**Comment by Shirajuki** [comment]
Hello again!
A new update of Anki-Redesign has just recently been pushed! Hopefully every issue is fixed here. I have added an addon config to fix this issue by entirely disabling my custom styling on the review buttons so that ARBb's styling is used instead. This fix can be enabled in Anki-redesign -> Config -> Addon-Compatibility Fixes. Closing! :D

**Comment by Shirajuki** [comment]
Uhm, I should probably have this issue open in case there are still some bugs in the update as this update was quite rushed.
