### ISSUE TITLE
[Bug} Filtered decks no longer have a different color

### ISSUE THREAD

**Issue by aly-k** [Shirajuki/anki-redesign#23]
Default behaviour without the addon: In the deck browser, normal decks have a white text color. While filtered decks have a light blue text color.

With the addon: all decks have a white text color.

i have no coding experience but i made the following changes to "DeckBrowser.css" that restored the default behaviour.

replace this part
```
body table:first-of-type tr a,
body table:first-of-type tr a.filtered {
  color: var(--text-fg, var(--legacy-text-fg)) !important;
}
```

with
``` 
body table:first-of-type tr a {
  color: var(--text-fg, var(--legacy-text-fg)) !important;
}
body table:first-of-type tr a.filtered {
  color: #81cfff !important;
} 
```

**Comment by Shirajuki** [comment]
Hello hello!
Thank you very much for the issue including a great fix as well. I forgot to consider that the text color of the different decks were supposed to be different haha! I'll be implementing your fix in the next update! My exams period are finally over, so expect an update in the near future this month! :D

Thank you for being a user of Anki-Redesign as well! 🥳

**Comment by Shirajuki** [comment]
Hello again! Took quite some time for me to find some development time to add the fix. But here it is!
Anki should prompt an update of Anki-redesign v0.1.3 on the addon for you now. :)
Hopefully everything works for now! Closing this issue! :D

**Comment by Shirajuki** [comment]
Ah also, feel free to repoen with a new issue if there ever happens to still not work. Thank you for helping with the development of Anki-Redesign! :D
