### ISSUE TITLE
Addon doesnt work on 2.1.22

### ISSUE THREAD

**Issue by Willz7** [Shirajuki/anki-redesign#3]
Hi @Shirajuki, the design looks really good.

I was hoping to use the add-on on Anki 2.1.22.

**Comment by Willz7** [comment]
Hi @Shirajuki, the design looks really good. 

I was hoping to use the add-on on Anki 2.1.22.

**Comment by Shirajuki** [comment]
Hi @Willz7!
Thank you for taking a look at my addon and testing it, seeing that Anki-redesign are appreciated makes me really happy! :D
I will have a look at that specific version, and hopefully it will be usable for you on the next update! :D
I'll update you on when it happens!

**Comment by Willz7** [comment]
> Hi @Willz7! Thank you for taking a look at my addon and testing it! Seeing that Anki-redesign is being appreciated makes me really happy! :D I will have a look at that specific version of Anki, and hopefully it will be usable for you on the next update of v0.0.3! :D I'll update you on when it gets manually tested and fixed!

Hi @Shirajuki, thank you for getting back to me, I did try to manually import the addon and I got this error 
![image](https://user-images.githubusercontent.com/5053219/149668619-bd0607f3-dc86-4350-9204-e3de89cb48e8.png)

**Comment by Shirajuki** [comment]
Heyo!
Thanks for the wait. I have been a little bit busy with semester start this week. I got the addon working on 2.1.22 now :D
Anki-redesign v0.0.3 will be released at an unknown time tomorrow :P. I hope this addon will be worth the wait though, and hopefully also of some use for you in your studies. Thank you for trying out the addon. :D

**Comment by Shirajuki** [comment]
The new update is now out 😊. Thank you for the wait! 🥳
