### ISSUE TITLE
Translation of extension (also translation into future versions)

### ISSUE THREAD

**Issue by chezfo** [Shirajuki/anki-redesign#31]
I want to translate this plugin into my language.
Does this extension support translation into languages, in a way that will also exist in future versions ??

**Comment by Shirajuki** [comment]
Hello chezfo! 
The code for Anki-redesign as of now does not support the translation of texts, unfortunately. This should however be made possible in the near future when most of the critical bugs with the new QT6 update is fixed. Adding new functionalities while the add-on is buggy is therefore not prioritized. Though, thank you very much for the nice suggestion and the thought of wanting to contribute to the add-on! I am very happy to know that the add-on is appreciated enough that someone wants to translate the add-on into their own language!

I'll bump this issue thread once the support of adding language translations is made possible, and hope it is okay for you to wait till then. Thank you once again! :D

**Comment by Shirajuki** [comment]
Hello again!
An update making it possible for you to add in translations is now available.
See #46 for a more detailed description. I'll have this issue open for now :)
