### ISSUE TITLE
Bug: some color settings are not available

### ISSUE THREAD

**Issue by Jerfain** [Shirajuki/anki-redesign#32]
Hello Shirajuki :D    I'm here againnnnnn with bug feedback.

First, let me show you what anki looks like after I modify the color scheme.

_The light theme_
<img width="960" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416590-28013a61-6a79-4d15-b482-9a3fe552d1a5.png">

_The dark theme_
<img width="960" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416647-06f451bd-ee77-4cba-bd0b-def126d1f86c.png">

Next I will give feedback on two bugs that I encountered during the modification process.

1. The color of the selected deck does not respond after modification, this problem occurs in both day mode and night mode.(Of course I'm sure I saved the changes after I made them)
<img width="1220" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416729-ef2e2612-e347-4e0d-9567-eaccd19f1769.png">
<img width="1301" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416733-e4feab60-a9a0-48be-87cb-fe9790c1583b.png">

2. The frame background color does not respond after modification, but appears only in night mode.
<img width="1314" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416761-767f6862-bb3b-4f12-96d5-b0a873d6c33f.png">

_This problem is not present in daytime mode._
<img width="1237" alt="图片" src="https://user-images.githubusercontent.com/69144012/179416767-ddf1748c-ecd0-4b5e-9fc1-8a4c982c0985.png">

In addition, I think I should not push you to update more themes, I think it is more important to change the color interface and make it easier to understand which position each option corresponds to, and then you can experience creating your own color scheme, but finally I propose a save as theme function, you can customize the changes under the current existing theme, and then save as a new theme that you can name yourself. I'm afraid that after the next redesign update my custom color scheme will be overwritten.

Lastly, I really like redesign and would love to find bugs for it, please don't feel pressured, this plugin is good enough.

**Comment by Jerfain** [comment]
I have another question, when the mouse hovers over a deck, a dark background will appear, I tried to extract the color of this background and find the corresponding color option in redesign settings (yes, currently I change the color is based on the color correspondence to determine which option corresponds to what position of anki, I think a guide can be issued to explain the corresponding position of each option), but I did not find the corresponding option of this background color, can you tell me which option corresponds?
<img width="960" alt="图片" src="https://user-images.githubusercontent.com/69144012/179417532-360195ce-2792-4cb0-97ff-e86f5b543776.png">

**Comment by Jerfain** [comment]
Today I tried to study the correspondence between each color setting and anki interface, I found that the original modification of the last selected color is by modifying the faint border, but this has a new problem, in the night mode to modify the faint border will lead to the color of the top bar is modified together, just echoed the modification of the frame background top bar color unchanged bug, but in the day mode will not have this problem.

<img width="1291" alt="图片" src="https://user-images.githubusercontent.com/69144012/179434750-590b8b7a-0aaa-4fda-bb91-19f26f9c1cd9.png">
<img width="1286" alt="图片" src="https://user-images.githubusercontent.com/69144012/179434747-a08dbbe7-bccc-4c66-b06c-aa2ee45f340a.png">

**Comment by Shirajuki** [comment]
Hello again Jerfain!
Thank you very much for such a nice and detailed bug report! To tell you the truth, the reason where some color settings were not correctly used even though you could edit it in the preferences was due to me making my add-on compatible with [AnKingMed's AnkiRecolor Add-on](https://github.com/AnKingMed/AnkiRecolor), which I discovered while working on my add-on.

I'll be addressing this issue hopefully on the next update! Thank you very much for liking and using Anki-redesign, as well as helping with the bug reports! It has been very helpful to map bugs that needs to be fixed!

**Comment by Shirajuki** [comment]
Heyoheyo!
A new version of Anki-redesign was just recently pushed out, adding a fix to the color settings not being correctly set. I have tried to manually fix this by changing the styling of the files. Hopefully I did not forget any details and everything looks good now. I'll be leaving this issue open for now. 🥳
