### ISSUE TITLE
Bug:The color switch on some pages is not working

### ISSUE THREAD

**Issue by Jerfain** [Shirajuki/anki-redesign#33]
It's me againnnnnnnnn.

This bug is just a simple little problem, and I just happen to have the timing right to find this bug.

Just when I was reporting on a bug about colors, I needed to switch modes to show the bug in a screenshot, and on the way I happened to open my stats page, and then I noticed that the background color of the stats page didn't change as naturally as the main page during the switch between day and night mode.

<img width="1674" alt="图片" src="https://user-images.githubusercontent.com/69144012/179417822-dee41f8b-24c0-48b9-b6c5-ce6321a11415.png">
<img width="1674" alt="图片" src="https://user-images.githubusercontent.com/69144012/179417821-89e84b62-da80-4540-9794-9e0bff437843.png">

Then I stopped by to see if browsing page would also have this problem, and it turns out that it does.
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/179417915-a3396fe1-ebbf-4be5-a4b8-cf1caebd5681.png">
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/179417919-54bd51df-1429-4884-b678-274ebae2e03c.png">

But this page is browsed with the help of the plugin Browser: Table/Editor side-by-side (horizontal split), so I thought it might be a problem with the adaptability of the plugin, after I turned off the plugin and tried again, I found that the problem still existed ᇂдᇂ     , I only tried to switch from night to day, another switch I think there is no need to try.
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/179418041-e5590179-0cc1-4dba-8637-bb2d8ac06a23.png">

**Comment by Shirajuki** [comment]
Hello again!
Hmm, this bug seems to be closely related to #24, which to tell you the truth is not actually fixed correctly yet. 
I will definitely be taking a look at this in the next update!

A very detailed report as usual! Thank you! 😊

**Comment by Shirajuki** [comment]
Hello! Here to inform you that this problem should be fixed on the newly released update of v0.1.4! Hopefully it works for you now! :D
