### ISSUE TITLE
NDFS compatibility configuration problem

### ISSUE THREAD

**Issue by rwmpelstilzchen** [Shirajuki/anki-redesign#43]
Hi,

Thanks for making and maintaining Anki Redesign! It greatly improves the experience of using Anki ^_^

I see there is a new fix for NDFS compatibility. If I check the relevant checkbox on the Anki Redesign configuration window and click *Save*, it returns to an unchecked state when I revisit the configuration window, and doesn’t have any effect on the interface (even after restarting Anki).

It does seem to work if I bypass the configuration by changing 

https://github.com/Shirajuki/anki-redesign/blob/68483dbb01f794e8245ce8e2ddf823a0109fc007/config.py#L8

into

```python
config['addon_no_distractions_full_screen'] = True# if config.get('addon_no_distractions_full_screen', "false").lower() == "true" else False
```

**Comment by Shirajuki** [comment]
I guess I made an opsies there. An update fixing this will be up shortly!

**Comment by Shirajuki** [comment]
A fix was just added, will be pushing this fix together win a new update soon! Thank you for the patience!
