### ISSUE TITLE
Update to 2.1.55

### ISSUE THREAD

**Issue by galantra** [Shirajuki/anki-redesign#44]
Beta 1 of Anki 2.1.55 is out now. It features various UI changes: https://betas.ankiweb.net/anki2.1.55.html

In particular, I've noticed that the custom color doesn't get applied to the inside of the fields in the editor and browser-editor: 
![imagen](https://user-images.githubusercontent.com/52420923/192748559-f306ebbc-a2dc-409e-a15a-38fda6d2cb24.png)

Preferences screen:

![imagen](https://user-images.githubusercontent.com/52420923/192748918-63270150-8f4f-46bf-aaaa-a05d52ac174e.png)

Deck options screen:

![imagen](https://user-images.githubusercontent.com/52420923/192749801-e203197d-7f76-4491-91c6-f206b0951704.png)

**Comment by kvn1351** [comment]
Things I've noticed that are broken, there might be more:

- Reviewer.css isn't loaded.
- QtButtons, Selection boxes etc aren't themed anymore
- In the editor, the field backgrounds aren't themed.  `--canvas-elevated` is the variable they've introduced for that color.

**Comment by Shirajuki** [comment]
Rip 🙃 

I have been travelling around while doing my studies since summer and haven't had the time to work on the addon thus far. I'll however be back in action this month with Hacktoberfest and all ;) Thank you very much for the issue @galantra and @kvn1351, having images and a list of points with broken things does help me a lot in producing a fix faster! 💪

**Comment by FreyaDC** [comment]
Hi! Wanted to let you know the addon gives an error in the beta 3 version of Anki 2.1.55 that was just released. 

On startup:
`Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Anki-redesign⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\freya\AppData\Roaming\Anki2\addons21\308574457\__init__.py", line 259, in <module>
    from .utils import dialog
  File "C:\Users\freya\AppData\Roaming\Anki2\addons21\308574457\utils\dialog.py", line 491, in <module>
    update_theme()
  File "C:\Users\freya\AppData\Roaming\Anki2\addons21\308574457\utils\dialog.py", line 420, in update_theme
    apply_theme(ncolors)
  File "C:\Users\freya\AppData\Roaming\Anki2\addons21\308574457\utils\dialog.py", line 462, in apply_theme
    theme_manager._apply_palette(mw.app) # Update palette theme_manager
  File "aqt.theme", line 286, in _apply_palette
  File "aqt.theme", line 187, in qcolor
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str
⁩`

On opening the Browser:
`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (e5c4ccf0) Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22000
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-28 19:37:08

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 43, in cmd
  File "aqt.webview", line 150, in _onCmd
  File "aqt.webview", line 612, in _onBridgeCmd
  File "aqt.toolbar", line 168, in _linkHandler
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1158, in onBrowse
  File "aqt", line 130, in open
  File "aqt.browser.browser", line 133, in __init__
  File "aqt.browser.browser", line 613, in setupSidebar
  File "aqt.browser.sidebar.tree", line 95, in __init__
  File "aqt.browser.sidebar.tree", line 107, in _setup_style
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str
`

**Comment by Ben-Judah** [comment]
Hello all.

Just wanted to share that using beta3 led me to the same problem. However, the add-on works perfectly in beta2

**Comment by Shirajuki** [comment]
Hello again!
Just released an update adding a partially compatibility fix for 2.1.56. The addon should hopefully startup and apply the color changes correctly without any errors now. Currently, only the theme Anki is actually styled correctly, but I'll be working on fixing the styling for the other themes as well as actually testing the addon on 2.1.55 and 2.1.57 for the next update. Hopefully it won't take to long again.

Thank you all for the patience and support all along!
I'll let the issue be open for further discussions and occurring problems if any :)

**Comment by Shirajuki** [comment]
Hello!
Updating that a new version of Anki-redesign was just recently released. This adds a lot of bugfixes, and should be compatible with Anki 2.1.57 now! I'll be closing this issue for now, feel free to create new issues if there is still any bugs still occuring.

Thank you all for the patience and support all along!

**Comment by Ben-Judah** [comment]
Thank you very much!
