### ISSUE TITLE
New release does not apply theme to upper window bar in windows

### ISSUE THREAD

**Issue by AboShayeb** [Shirajuki/anki-redesign#55]
I don't know if what I wrote in the title makes sense, but I hope the image does the trick. So, in the previous release this white bar was colored black accordingly with the theme, but now it is this awful white like original anki design.

![image](https://user-images.githubusercontent.com/52991439/198540020-c1d9768e-88b6-4ca9-8a94-7b95ca24c193.png)

**Comment by Shirajuki** [comment]
Hello again!
I just recently added a new update adding a fix to this!

Thank you for the support all along :)
