### ISSUE TITLE
Light Mode Error in Add Window

### ISSUE THREAD

**Issue by Kitsune912** [Shirajuki/anki-redesign#6]
The image says it all:
![image](https://user-images.githubusercontent.com/81825142/150418478-fb088fa8-b9e2-4fc8-80f1-6cb7a61a1053.png)

**Comment by Shirajuki** [comment]
Hello @Kitsune912
First of all, thank you for testing out at Anki-redesign! I happy to see that Anki-redesign is actually being used, and issues are being made! :D
From the looks of it, it seems that I have forgotten to remove a forced background-color to AddCards after testing with the styling of dialog windows. It wasn't really supposed to be part of the release yet as I haven't actually begun styling the dialog windows yet. I will shortly push a fixed release due today, and hopefully it will be looking better for you after the update! :D
I'll update you on when it gets fixed!

**Comment by Kitsune912** [comment]
Thanks ;)

**Comment by Shirajuki** [comment]
Hello again!
I have now fixed the issue, you can update the addon by going to "Tools" -> "Add-ons" -> "Check for Updates" :D
Thank you for your patience! I hope you will look forward to the future updates planned in the future. 🥳

**Comment by Kitsune912** [comment]
Sure I will :)
