### ISSUE TITLE
Horizontal Slider

### ISSUE THREAD

**Issue by Hosseingsd** [Shirajuki/anki-redesign#60]
Why the horizontal slider appears while there is a lot of space left for zoom??

![slider](https://user-images.githubusercontent.com/110593678/211186883-3fb724ff-2ea0-45a3-8f3d-187c8f8f00d4.png)

![slider 2](https://user-images.githubusercontent.com/110593678/211187195-ddb217b0-ef2a-430c-882c-c9f137bba436.png)

**Comment by Shirajuki** [comment]
Hello hello!
I have just recently added a new update of Anki-redesign hopefully fixing this.
If the problem still occurs, feel free to open a new issue. Thank you for being a user of Anki-redesign! :)

I'll be closing this issue!

**Comment by Hosseingsd** [comment]
Hello.
Thank you for you attention.
I checked: this is issue with[ "**Enhance Main Window**" addon.](https://github.com/Arthur-Milchior/anki-enhance-main-window).
