### ISSUE TITLE
Cut bottom on card view

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#7]
Here the numbers are a bit cut

![Kuvakaappaus 2022-01-24 14-47-13](https://user-images.githubusercontent.com/57091497/150794377-f2659782-c19b-4e77-9a82-edc88abd8336.png)

**Comment by Shirajuki** [comment]
Hello! First, I would like to give you my thanks for testing out at Anki-redesign and contributing to making it a better addon for everyone!
From the looks of it, it seems that the padding values of the styling has overflown the AnkiWebView. I have released an update (v0.0.5) to the addon along with the fix to this. Hopefully it will be looking better for you after the update! :D

I'll keep the issue open in case the fix did not work for you. If that ever happens, send me the anki version you're using along with the enabled addons, that would help me a lot with the debugging! :D 
Thank you for being an user of Anki-redesign!
